# Generated by Django 5.1.5 on 2025-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_memberlevel_sale_discount_amount_sale_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
