# Generated by Django 5.1.5 on 2025-03-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_member_gender_member_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Standard Price'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SALE', 'Sale'), ('INVENTORY', 'Inventory Adjustment'), ('MEMBER', 'Member Management'), ('OTHER', 'Other')], max_length=20, verbose_name='Operation Type')),
                ('details', models.TextField(verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('related_object_id', models.PositiveIntegerField(verbose_name='Related Object ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Related Content Type')),
            ],
            options={
                'verbose_name': 'Operation Log',
                'verbose_name_plural': 'Operation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
