# Generated by Django 5.1.5 on 2025-03-29 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_member_birthday_member_purchase_count_product_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='notes',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='member',
            name='notes',
        ),
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account Balance'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_recharged',
            field=models.BooleanField(default=False, verbose_name='Is Recharged Member'),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance Payment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('card', 'Bank Card'), ('balance', 'Account Balance'), ('mixed', 'Mixed Payment'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered At'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Recharge Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('card', 'Bank Card'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('remark', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recharged At')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to='inventory.member', verbose_name='Member')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Recharge Record',
                'verbose_name_plural': 'Recharge Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
